add_newline = true

[character]
symbol = "?"

[directory]
truncation_length = 100
truncate_to_repo = false

[aws]
style = "bold blue"
symbol = "? "
displayed_items = "all"

[aws.region_aliases]
ap-northeast-1 = "jp"

[memory_usage]
disabled = false
show_percentage = true
show_swap = true
threshold = -1
symbol = " "
separator = "/"
style = "bold dimmed blue"

[package]
disabled = true
